version: '3'
services:
  eureka:
    build: ./eureka
    ports:
        - "8761:8761"
    container_name: eureka-jar

  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    environment:
      - EUREKA_URL:http://eureka:8761/eureka/
    container_name: gateway-jar
    depends_on:
      - "eureka"

  database:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=artemi
      - MONGO_INITDB_ROOT_PASSWORD=2424285
    container_name: mongo-db

  message-broker:
    image: rabbitmq:management
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=artemi
      - RABBITMQ_DEFAULT_PASS=2424285
    container_name: message-broker

  consumer:
    build: ./consumer
    ports:
      - "8081:8080"
    environment:
      - MONGO_DATABASE=database
      - MONGO_HOST=database
      - MONGO_PORT=27017
      - MONGO_PASSWORD=2424285
      - MONGO_USERNAME=artemi
      - RABBITMQ_HOST=message-broker
      - RABBITMQ_PASSWORD=2424285
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=artemi
    container_name: consumer-jar
    depends_on:
      - "database"
      - "eureka"
      - "gateway"
      - "message-broker"
      - "producer"

  producer:
    build: ./producer
    ports:
      - "8082:8080"
    environment:
      - MONGO_DATABASE=database
      - MONGO_HOST=database
      - MONGO_PORT=27017
      - MONGO_PASSWORD=2424285
      - MONGO_USERNAME=artemi
      - RABBITMQ_HOST=message-broker
      - RABBITMQ_PASSWORD=2424285
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=artemi
    container_name: producer-jar
    depends_on:
      - "database"
      - "eureka"
      - "gateway"
      - "message-broker"
