spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: producer
          uri: lb://producer
          predicates:
            - Path=/api/v1/auth/**
        - id: consumer
          uri: lb://consumer
          predicates:
            - Path=/api/v1/stats/**
